### ISSUE TITLE
Discussion about a Variable entry Interface

### ISSUE THREAD

**Issue by Thore-Krug** [ArchEvo/ArchEvo#1]
The skript uses variables to create and set up the following things during the Installation Process: 

1. The Username
2. The Password
3. The Timezone 
4. and more.. 

In the current state of the script you would need to change these variables yourself according to your needs.

There are various options for a interface to enter the rquired data: 

1.  Via the bash script itself 
2. dialog/whiptail
3. kconfig
4. UIs such a QT or YAD

 Using the bash script as enty method has the advantage a eased implementation but a disadvantage in entering data which a large amount of variations such as the location and timezone. making the UI crowded and difficult to navigate. 

Using a framework such as dialog and whiptail makes it easy to create graphical and intuitive Interfaces but need a bit more work to implement. 

kconfig can be used to create the same interfaces available with dialog and whiptail but can be configured via a config. The output of kconfig itseld would be handy requires more work to implement though as the information needs to be filtered and made available for the setup scripts- 

UI Frameworks have the by far the best UX but are difficult to set up and would require a xserver to be running making it unsuitable for the purpose of the script. 

I am looking towards a discussion on this topic. 

Signed off by Thore Krug 

opensource[at]thorekrug.de

**Comment by StellarCollision** [comment]
Hello Thore Krug,

thank you for your contribution!

I thought about the implementation of the input of the variables. Of course the current solution is bad.

My thoughts:

- Graphic installer aka XServer or Wayland makes a lot of trouble

- kconfig doesn't seem to be a good solution (very complex)

- The best solution is probably dialog or whiptail (simple and easy)

No matter what the solution looks like in the end. The aim is to find an understandable and simple solution.

If you have the time and desire, then we would be happy if you support us.



StellarCollision
